export type ProviderHealth = { status: string; embedding: { namespace: string; dev_quality: boolean; status: string; provider: string; model: string; dimensions?: number; normalized?: boolean } };

export type Workspace = { id: string; name: string; slug: string };
export type Project = { id: string; workspace_id: string; name: string; description: string | null; visibility: string };
export type User = { id: string; email: string; display_name: string | null; is_active: boolean; is_platform_admin: boolean; created_at: string | null };
export type WorkspaceMember = { id: string; workspace_id: string; user: User; role: string; created_at: string | null };
export type CurrentUserResponse = { user: User; workspaces: Workspace[]; memberships: WorkspaceMember[]; projects_by_workspace: Record<string, Project[]>; default_workspace_id: string | null; default_project_id: string | null };
export type LoginResponse = CurrentUserResponse & { session_token: string };
export type AuditEvent = { id: string; workspace_id: string; actor_user_id: string | null; actor_token_id: string | null; action: string; target_type: string; target_id: string | null; target_ref: Record<string, unknown>; metadata: Record<string, unknown>; created_at: string };

export type AgentProfile = {
  id: string;
  workspace_id: string;
  project_id: string;
  name: string;
  description: string | null;
  default_runtime: string;
  system_prompt: string | null;
  tool_policy: Record<string, unknown>;
  resource_count: number;
  current_snapshot_count: number;
  graph_node_count: number;
  graph_edge_count: number;
  last_index_finished_at: string | null;
  mcp_endpoint: string;
  agent_context_endpoint: string;
  created_at?: string | null;
  updated_at?: string | null;
};

export type Resource = {
  id: string;
  workspace_id: string;
  project_id: string;
  type: string;
  name: string;
  uri: string;
  status: string;
  retrieval_enabled: boolean;
  update_frequency: string;
  current_snapshot_id: string | null;
  review_status: string;
  review_note: string | null;
  last_reviewed_at?: string | null;
  last_reviewed_by?: string | null;
  archived_at: string | null;
  deleted_at: string | null;
  next_refresh_at: string | null;
  last_refresh_started_at?: string | null;
  last_refresh_finished_at: string | null;
  stale_after_days: number;
  source_family_label?: string | null;
  version_label?: string | null;
  has_manifest_diff?: boolean;
};

export type ReviewItem = { resource: Resource; freshness_status: string; freshness_age_days: number | null; usage_count: number; last_used_at: string | null; last_index_status: string | null; last_index_finished_at: string | null; stale_reasons: string[] };
export type UsageItem = { resource_id: string; query_count: number; hit_count: number; context_packet_count: number; last_used_at: string | null };
export type AgentFile = { path: string; kind: string; description: string; content: string };
export type AgentFilesResponse = { workspace_id: string; project_id: string; generated_at: string; resource_count: number; repo_agent_count: number; files: AgentFile[] };
export type RemoteGrepMatch = { resource_id: string; snapshot_id: string; indexed_commit: string | null; path: string; line_start: number; line_end: number; line_text: string; before: string[]; after: string[] };
export type RemoteGrepResponse = { matches: RemoteGrepMatch[]; next_cursor: string | null; truncated: boolean };
export type RemoteReadFileResponse = { resource_id: string; snapshot_id: string; indexed_commit: string | null; path: string; start_line: number; end_line: number; total_lines: number; content: string; truncated: boolean };
export type GitResourceEnv = { resource_id: string; name: string; uri: string; branch: string | null; auth_token_env: string | null; clone_timeout: number | null; max_file_bytes: number | null; max_repo_files: number | null; max_repo_bytes: number | null; update_frequency: string; next_refresh_at: string | null };
export type AgentCardSummary = { id: string; workspace_id: string; project_id: string; resource_id: string; status: string; severity: string; summary: string; findings: Array<Record<string, unknown>>; metrics: Record<string, unknown>; source: string; acknowledged_at: string | null; acknowledged_by: string | null; suppressed_until: string | null; created_at: string };
export type AgentCardSummaryList = { count: number; summaries: AgentCardSummary[] };
export type PatchProposal = { id: string; workspace_id: string; project_id: string; resource_id: string; source_snapshot_id: string; status: string; scope: string; source_branch: string | null; target_branch: string | null; indexed_commit: string | null; base_commit: string | null; branch_moved: boolean; warnings: string[]; files: Array<Record<string, unknown>>; unified_diff: string; diff_summary: string; created_at: string };
export type PrRequest = { id: string; workspace_id: string; project_id: string; resource_id: string; patch_proposal_id: string; status: string; source_branch: string; target_branch: string; scope: string; diff_summary: string; approval_note: string; github_pr_url: string | null; external_ref: Record<string, unknown>; created_at: string };
export type RepoAgentBrief = { resource_id: string; name: string; uri: string; readiness: string; current_snapshot_id: string | null; branch: string | null; commit: string | null; update_frequency: string; freshness: Record<string, unknown>; stats: Record<string, number>; operating_brief: string; entrypoint_paths: string[]; config_paths: string[]; runtime_paths: string[]; runbook_paths: string[]; symbol_samples: Array<Record<string, unknown>>; suggested_questions: string[]; invocation: Record<string, unknown>; safety_boundary: string; quality_gates: string[] };
export type RetrievalEvalQuestion = { id: string; query: string; expected_resource_ids: string[]; forbidden_resource_ids?: string[]; resource_ids?: string[]; expected_paths?: string[]; expected_symbols?: string[]; required_texts?: string[]; min_citations?: number; top_k?: number; include_code_symbols?: boolean };
export type RetrievalEvalResult = { id: string; query: string; passed: boolean; failure_reasons: string[]; latency_ms: number; citation_count: number; context_chars: number; symbol_count: number; expected_resource_ids: string[]; cited_resource_ids: string[]; forbidden_resource_ids: string[]; hit_quality: Array<Record<string, unknown>> };
export type RetrievalProfile = { name: string; description: string; weights: Record<string, number> };
export type RetrievalProfilesResponse = { default: string; profiles: RetrievalProfile[] };
export type RetrievalEvalResponse = { run_id?: string | null; profile: string; workspace_id: string; project_id: string; generated_at: string; provider: string; model: string; diagnostics: Record<string, unknown>; summary: { status: string; question_count: number; passed_count: number; failed_count: number; pass_rate: number; max_latency_ms: number; avg_latency_ms: number; failure_reasons: string[] }; results: RetrievalEvalResult[] };
export type RetrievalEvalRunSummary = { id: string; profile: string; workspace_id: string; project_id: string; created_at: string; runtime: string; provider: string; model: string; status: string; question_count: number; passed_count: number; failed_count: number; pass_rate: number; max_latency_ms: number; avg_latency_ms: number; project_wide: boolean; resource_ids: string[]; failure_reasons: string[] };
export type RetrievalEvalRunList = { count: number; runs: RetrievalEvalRunSummary[] };
export type DueRefreshResponse = { scanned: number; enqueued: number; resource_ids: string[]; skipped_active: string[]; dry_run: boolean };
export type Snapshot = { id: string; workspace_id?: string; project_id?: string; resource_id?: string; version: string; version_kind: string; status: string; metadata: Record<string, unknown>; fetched_at: string | null; indexed_at: string | null; created_at?: string | null; is_current: boolean };
export type IndexRun = { id: string; resource_id: string; snapshot_id: string | null; status: string; trigger: string; documents_seen: number; chunks_created: number; chunks_reused: number; symbols_created: number; embeddings_created: number; graph_nodes_created: number; graph_edges_created: number; error_message: string | null; finished_at: string | null; started_at?: string | null; created_at?: string | null };
export type ResourceManifestFile = { id: string; normalized_path: string; display_path: string | null; size_bytes: number; content_hash: string; mime_type: string | null; status: string; warnings_json: string[] };
export type ResourceManifest = { id: string; resource_id: string; source_snapshot_id: string; manifest_hash: string; file_count: number; total_bytes: number; parser_warning_count: number; unsupported_file_count: number; created_at: string; files: ResourceManifestFile[] };
export type ManifestDiffRow = { normalized_path: string; change_type: string; base_file_id: string | null; head_file_id: string | null; base_status: string | null; head_status: string | null; base_size_bytes: number | null; head_size_bytes: number | null; base_content_hash: string | null; head_content_hash: string | null; warning_changed: boolean; reason: string };
export type ManifestDiff = { base_manifest_id: string; head_manifest_id: string; base_resource_id: string; head_resource_id: string; source_family_label: string | null; added_count: number; changed_count: number; deleted_count: number; unchanged_count: number; warning_changed_count: number; base_file_count: number; head_file_count: number; total_row_count: number; row_count_returned: number; limit: number; next_cursor: string | null; rows: ManifestDiffRow[]; deleted_file_impact: { deleted_file_count: number; impacted_sections_known: boolean; message: string } };
export type FolderBundleUploadResponse = { resource: Resource; index_run: IndexRun };
export type GraphRead = { node_count: number; edge_count: number; nodes: Array<{ id: string; resource_id: string; snapshot_id: string; node_key: string; node_type: string; label: string; path: string | null; metadata: Record<string, unknown> }>; edges: Array<{ id: string; resource_id: string; snapshot_id: string; source_node_id: string; target_node_id: string; edge_type: string; weight: number; metadata: Record<string, unknown> }> };
export type CodeSymbol = { resource_id: string; snapshot_id: string; path: string; name: string; kind: string; language: string; line_start: number; line_end: number; signature: string; content_hash: string; version: string; version_kind: string; commit: string | null; score: number };
export type AgentCitation = { resource_id: string; snapshot_id: string; chunk_id: string; path: string | null; title: string | null; ordinal: number; score: number; graph_score: number; version: string; version_kind: string; commit: string | null };
export type AgentContextResponse = { query: string; profile: string; runtime: string; instruction: string; context: string; citations: AgentCitation[]; token_budget_hint: number; symbols: CodeSymbol[] };
export type ApiToken = { id: string; workspace_id?: string; name: string; scopes: string[]; allowed_project_ids: string[] | null; allowed_resource_ids: string[] | null; revoked_at: string | null; created_at: string | null; last_used_at: string | null; expires_at?: string | null; created_by?: string | null };
export type TokenCreateResponse = { token: string; api_token: ApiToken };
