from __future__ import annotations

import hashlib
import re
import shlex
import shutil
from datetime import UTC, datetime
from pathlib import Path
from typing import Literal, cast

from pydantic import BaseModel, ConfigDict, Field

from sourcebrief_shared.regression_proposal import RegressionProposal
from sourcebrief_shared.validation_gate import ValidationGateResult

STAGED_ADOPTION_RECEIPT_SCHEMA_VERSION: Literal["sourcebrief.staged-adoption-receipt.v1"] = "sourcebrief.staged-adoption-receipt.v1"
StageDecision = Literal["accept", "accept_new_best"]
StageFileKind = Literal["proposal", "gate_result", "patch", "summary"]


class StagedAdoptionError(ValueError):
    """User-facing staged adoption error."""


class StrictModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class StagedFile(StrictModel):
    path: str = Field(min_length=1)
    kind: StageFileKind
    sha256: str = Field(pattern=r"^sha256:[a-f0-9]{64}$")
    bytes: int = Field(ge=0)


class StagedAdoptionReceipt(StrictModel):
    schema_version: Literal["sourcebrief.staged-adoption-receipt.v1"] = STAGED_ADOPTION_RECEIPT_SCHEMA_VERSION
    stage_id: str = Field(min_length=1)
    proposal_id: str = Field(min_length=1)
    gate_result_id: str = Field(min_length=1)
    gate_decision: StageDecision
    source_report_id: str = Field(min_length=1)
    source_bundle_id: str = Field(min_length=1)
    source_finding_id: str = Field(min_length=1)
    target_surface: str = Field(min_length=1)
    stage_dir: str = Field(min_length=1)
    files: list[StagedFile] = Field(min_length=1)
    patch_path: str = Field(min_length=1)
    apply_command: str = Field(min_length=1)
    rollback_command: str = Field(min_length=1)
    discard_stage_command: str = Field(min_length=1)
    apply_args: list[str] = Field(min_length=2)
    rollback_args: list[str] = Field(min_length=3)
    discard_stage_args: list[str] = Field(min_length=3)
    human_review_required: bool = True
    status: Literal["staged"] = "staged"
    rationale: str = Field(min_length=1)
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


def load_regression_proposal(path: str | Path) -> RegressionProposal:
    return RegressionProposal.model_validate_json(Path(path).read_text(encoding="utf-8"))


def load_validation_gate_result(path: str | Path) -> ValidationGateResult:
    return ValidationGateResult.model_validate_json(Path(path).read_text(encoding="utf-8"))


def _safe_id(value: str) -> str:
    lowered = value.lower()
    safe = re.sub(r"[^a-z0-9._-]+", "-", lowered).strip("-._")
    return safe[:96] or "proposal"


def _sha256_bytes(data: bytes) -> str:
    return "sha256:" + hashlib.sha256(data).hexdigest()


def _file_record(path: Path, *, kind: StageFileKind, base_dir: Path) -> StagedFile:
    data = path.read_bytes()
    return StagedFile(
        path=str(path.relative_to(base_dir)),
        kind=kind,
        sha256=_sha256_bytes(data),
        bytes=len(data),
    )


def _escape_markdown(value: str | None) -> str:
    if not value:
        return "(none)"
    return value.replace("\r\n", "\n").replace("\r", "\n")


def staged_note_path(proposal: RegressionProposal) -> str:
    safe = _safe_id(proposal.proposal_id)
    if proposal.target_surface in {"docs", "skill", "runtime_pack"}:
        return f"docs/self-improvement/staged-proposals/{safe}.md"
    if proposal.target_surface in {"test", "eval_fixture"}:
        return f"docs/examples/self-improvement/staged-regressions/{safe}.md"
    return f"docs/self-improvement/staged-proposals/{safe}.md"


def staged_note_content(proposal: RegressionProposal, gate_result: ValidationGateResult) -> str:
    acceptance = "\n".join(f"- {item}" for item in proposal.acceptance)
    evidence = "\n".join(f"- {item}" for item in proposal.evidence_refs) or "- (none)"
    claims = "\n".join(f"- {item}" for item in proposal.claim_ids) or "- (none)"
    return (
        f"# Staged self-improvement proposal: {proposal.proposal_id}\n\n"
        "This file is generated by `sourcebrief review stage` as a human-reviewable patch. "
        "Applying it does not change runtime behavior; it records the accepted proposal so a developer can implement the smallest scoped follow-up.\n\n"
        "## Source\n\n"
        f"- Proposal: `{proposal.proposal_id}`\n"
        f"- Gate result: `{gate_result.gate_result_id}` (`{gate_result.decision}`)\n"
        f"- Review report: `{proposal.source_report_id}`\n"
        f"- Review bundle: `{proposal.source_bundle_id}`\n"
        f"- Finding: `{proposal.source_finding_id}`\n"
        f"- Target surface: `{proposal.target_surface}`\n\n"
        "## Failure mode\n\n"
        f"{_escape_markdown(proposal.failure_mode)}\n\n"
        "## Claim / evidence anchors\n\n"
        f"Claim: {_escape_markdown(proposal.claim)}\n\n"
        "Claim IDs:\n"
        f"{claims}\n\n"
        "Evidence refs:\n"
        f"{evidence}\n\n"
        "## Proposed regression check\n\n"
        f"{_escape_markdown(proposal.proposed_check)}\n\n"
        "## Suggested fix\n\n"
        f"{_escape_markdown(proposal.suggested_fix)}\n\n"
        "## Acceptance criteria\n\n"
        f"{acceptance}\n\n"
        "## Gate rationale\n\n"
        f"{_escape_markdown(gate_result.reason)}\n\n"
        "## Adoption boundary\n\n"
        "This staged note is not an adopted lesson, prompt, skill, runtime pack, or code change. "
        "A developer must inspect the receipt, apply the patch explicitly, and implement any real product/test changes in a separate reviewed commit or PR.\n"
    )


def unified_new_file_patch(path: str, content: str) -> str:
    lines = content.splitlines()
    body = "\n".join(f"+{line}" for line in lines)
    return (
        f"diff --git a/{path} b/{path}\n"
        "new file mode 100644\n"
        "--- /dev/null\n"
        f"+++ b/{path}\n"
        f"@@ -0,0 +1,{len(lines)} @@\n"
        f"{body}\n"
    )


def validate_stage_inputs(proposal: RegressionProposal, gate_result: ValidationGateResult) -> None:
    if gate_result.proposal_id != proposal.proposal_id:
        raise StagedAdoptionError(
            f"gate result proposal_id {gate_result.proposal_id!r} does not match proposal {proposal.proposal_id!r}"
        )
    if gate_result.decision not in {"accept", "accept_new_best"}:
        raise StagedAdoptionError("only accepted gate results can be staged for adoption")
    failed_checks = sorted(name for name, status in gate_result.checks.items() if status == "fail")
    if failed_checks:
        raise StagedAdoptionError(f"accepted gate result has failed checks: {', '.join(failed_checks)}")
    if gate_result.rejected_learning is not None:
        raise StagedAdoptionError("accepted gate result must not contain rejected_learning")
    if proposal.status == "rejected":
        raise StagedAdoptionError("rejected proposals cannot be staged for adoption")
    if proposal.target_surface == "unknown":
        raise StagedAdoptionError("proposal target_surface must be known before staged adoption")


def stage_regression_proposal(
    *,
    proposal_path: str | Path,
    gate_result_path: str | Path,
    out_dir: str | Path,
) -> StagedAdoptionReceipt:
    source_proposal_path = Path(proposal_path).expanduser()
    source_gate_path = Path(gate_result_path).expanduser()
    proposal = load_regression_proposal(source_proposal_path)
    gate_result = load_validation_gate_result(source_gate_path)
    validate_stage_inputs(proposal, gate_result)

    safe = _safe_id(proposal.proposal_id)
    stage_dir = Path(out_dir).expanduser() / safe
    if stage_dir.exists() and any(stage_dir.iterdir()):
        raise StagedAdoptionError(f"stage directory already exists and is not empty: {stage_dir}")
    stage_dir.mkdir(parents=True, exist_ok=True)

    proposal_copy = stage_dir / "proposal.json"
    gate_copy = stage_dir / "gate-result.json"
    patch_path = stage_dir / "proposal.patch"
    summary_path = stage_dir / "README.md"
    receipt_path = stage_dir / "receipt.json"

    shutil.copyfile(source_proposal_path, proposal_copy)
    shutil.copyfile(source_gate_path, gate_copy)

    note_path = staged_note_path(proposal)
    note_content = staged_note_content(proposal, gate_result)
    patch_path.write_text(unified_new_file_patch(note_path, note_content), encoding="utf-8")

    apply_args = ["git", "apply", str(patch_path)]
    rollback_args = ["git", "apply", "-R", str(patch_path)]
    discard_stage_args = ["rm", "-rf", str(stage_dir)]
    apply_command = " ".join(shlex.quote(arg) for arg in apply_args)
    rollback_command = " ".join(shlex.quote(arg) for arg in rollback_args)
    discard_stage_command = " ".join(shlex.quote(arg) for arg in discard_stage_args)
    summary = (
        f"# Staged adoption: {proposal.proposal_id}\n\n"
        "This directory was generated by `sourcebrief review stage`. It has not applied any product, prompt, skill, runtime, or code mutation.\n\n"
        "## Files\n\n"
        "- `proposal.json`: source regression proposal artifact.\n"
        "- `gate-result.json`: accepted validation gate result.\n"
        "- `proposal.patch`: human-reviewable patch to record the staged improvement.\n"
        "- `receipt.json`: machine-readable receipt with source refs and rollback commands.\n\n"
        "## Explicit apply / rollback\n\n"
        f"Apply manually from the repository root only after review: `{apply_command}`\n\n"
        f"Rollback after applying: `{rollback_command}`\n"
    )
    summary_path.write_text(summary, encoding="utf-8")

    files = [
        _file_record(proposal_copy, kind="proposal", base_dir=stage_dir),
        _file_record(gate_copy, kind="gate_result", base_dir=stage_dir),
        _file_record(patch_path, kind="patch", base_dir=stage_dir),
        _file_record(summary_path, kind="summary", base_dir=stage_dir),
    ]
    accepted_decision = cast(StageDecision, gate_result.decision)
    receipt = StagedAdoptionReceipt(
        stage_id=f"stage-{safe}",
        proposal_id=proposal.proposal_id,
        gate_result_id=gate_result.gate_result_id,
        gate_decision=accepted_decision,
        source_report_id=proposal.source_report_id,
        source_bundle_id=proposal.source_bundle_id,
        source_finding_id=proposal.source_finding_id,
        target_surface=proposal.target_surface,
        stage_dir=str(stage_dir),
        files=files,
        patch_path=str(patch_path),
        apply_command=apply_command,
        rollback_command=rollback_command,
        discard_stage_command=discard_stage_command,
        apply_args=apply_args,
        rollback_args=rollback_args,
        discard_stage_args=discard_stage_args,
        rationale=(
            "Accepted proposal staged for explicit human review. No production behavior was changed by staging."
        ),
    )
    receipt_path.write_text(receipt.model_dump_json(indent=2) + "\n", encoding="utf-8")
    return receipt
